"""
Refresh data/recipes.json: a copy of every published recipe, served by
GitHub Pages so the site can still show recipes when Supabase is down.

Runs hourly from .github/workflows/snapshot.yml, and works locally too:

    python scripts/snapshot.py

Reads the same public URL and publishable key the site itself uses (from
assets/js/config.js), so it can only see what any visitor can see.

The file is rewritten only when the recipes actually changed, so an
unchanged site produces no commit. If Supabase can't be reached the old
snapshot is left alone and the script exits 0 with a warning: an outage is
exactly when that snapshot is needed, and failing the job every hour would
just be email noise.
"""

import datetime as dt
import json
import re
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "assets" / "js" / "config.js"
OUT = ROOT / "data" / "recipes.json"

# Keep in sync with RECIPE_FIELDS in assets/js/data.js.
FIELDS = (
    "id,slug,title,blurb,hero_url,category,ingredients,steps,prep_minutes,"
    "cook_minutes,servings,published,review_count,rating_sum,created_at,updated_at"
)


def warn(message: str) -> None:
    # Rendered as an annotation on the Actions run; plain text locally.
    print(f"::warning::{message}")


def read_config() -> tuple[str, str]:
    text = CONFIG.read_text(encoding="utf-8")
    url = re.search(r"SUPABASE_URL:\s*'([^']+)'", text)
    key = re.search(r"SUPABASE_ANON_KEY:\s*'([^']+)'", text)
    if not url or not key:
        sys.exit("Could not find SUPABASE_URL / SUPABASE_ANON_KEY in config.js")
    return url.group(1), key.group(1)


def fetch_recipes(url: str, key: str) -> list[dict]:
    endpoint = (
        f"{url}/rest/v1/recipes?select={FIELDS}"
        "&published=eq.true&order=created_at.desc"
    )
    request = urllib.request.Request(
        endpoint,
        headers={"apikey": key, "Authorization": f"Bearer {key}", "User-Agent": "filipcooks-snapshot"},
    )
    last_error = None
    for attempt in range(4):
        try:
            with urllib.request.urlopen(request, timeout=20) as response:
                return json.loads(response.read())
        except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as error:
            last_error = error
            time.sleep(2 ** attempt)
    raise RuntimeError(f"Supabase unreachable after retries: {last_error}")


def main() -> int:
    url, key = read_config()

    try:
        recipes = fetch_recipes(url, key)
    except RuntimeError as error:
        warn(f"{error}. Keeping the existing snapshot.")
        return 0

    existing = None
    if OUT.exists():
        try:
            existing = json.loads(OUT.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            existing = None

    previous = (existing or {}).get("recipes") or []

    # An empty result while we already hold recipes is far more likely to be
    # a glitch than every recipe being unpublished at once. Don't wipe the
    # safety net on a hunch; unpublishing everything can be done by hand.
    if not recipes and previous:
        warn("Supabase returned no published recipes; keeping the existing snapshot.")
        return 0

    if recipes == previous and existing and existing.get("generated_at"):
        print(f"No changes ({len(recipes)} recipes).")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "generated_at": dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat(),
        "note": "Generated by scripts/snapshot.py. Do not edit by hand.",
        "recipes": recipes,
    }
    OUT.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Snapshot updated: {len(recipes)} recipes.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
